import {Montserrat} from "next/font/google"
import "./globals.css";

const mon = Montserrat({
  weight: '300',
  subsets: ['latin'],
})

export const metadata = {
  title: "Portfolio",
  description: "Generated by create Portfolio app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${mon.className} `}
      >
        {children}
      </body>
    </html>
  );
}
